kind: Deployment
apiVersion: apps/v1
metadata:
  name: preprocessor
spec:
  selector:
    matchLabels:
      app: preprocessor
  template:
    metadata:
      labels:
        app: preprocessor
    spec:
      containers:
      - name: preprocessor
        image: bhutaniarnav/producer
        env:
         - name: KAFKA_HOST_NAME
           value: kafka-service-pre

