kind: Deployment
apiVersion: apps/v1
metadata:
  name: processor
spec:
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - name: processor
        image: bhutaniarnav/consumer
        env:
         - name: KAFKA_HOST_NAME
           value: kafka-service-pre

