kind: Deployment
apiVersion: apps/v1
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: bhutaniarnav/worker
        env:
         - name: KAFKA_HOST_NAME
           value: kafka-service-train

